package com.neuedu.my12306;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by Gavin on 2016/1/6.
 */
public class CommonServer {
    public static List<Map<String, Object>> trainInformation;//车次信息
    public static void getInstance(){
        trainInformation = new ArrayList<Map<String, Object>>();
        Map<String, Object> train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-21");
        train_map.put("trainNo", "3306");
        train_map.put("source", R.drawable.flg_shi);
        train_map.put("destination",R.drawable.flg_zhong);
        train_map.put("startTime","08:30");
        train_map.put("stopTime","20:39(0日)");
        train_map.put("seat1","硬卧:56");
        train_map.put("seat2", "硬座:456");
        train_map.put("seat3", "无座:222");
        train_map.put("seat4", null);
        trainInformation.add(train_map);
        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-21");
        train_map.put("trainNo","D78");
        train_map.put("source",R.drawable.flg_guo);
        train_map.put("destination",R.drawable.flg_guo);
        train_map.put("startTime","07:30");
        train_map.put("stopTime","15:39(0日)");
        train_map.put("seat1","一等座:45");
        train_map.put("seat2","二等座:56");
        train_map.put("seat3", "无座:456");
        train_map.put("seat4", null);
        trainInformation.add(train_map);
        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-21");
        train_map.put("trainNo","Z102");
        train_map.put("source",R.drawable.flg_guo);
        train_map.put("destination",R.drawable.flg_zhong);
        train_map.put("startTime","19:30");
        train_map.put("stopTime","14:49(1日)");
        train_map.put("seat1","软卧:38");
        train_map.put("seat2","硬卧:86");
        train_map.put("seat3", "硬座:456");
        train_map.put("seat4", "无座:312");
        trainInformation.add(train_map);
        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-21");
        train_map.put("trainNo","K277");
        train_map.put("source",R.drawable.flg_guo);
        train_map.put("destination",R.drawable.flg_guo);
        train_map.put("startTime","07:30");
        train_map.put("stopTime","15:39(0日)");
        train_map.put("seat1","软卧:45");
        train_map.put("seat2","硬卧:56");
        train_map.put("seat3","硬座:456");
        train_map.put("seat4", "无座:222");
        trainInformation.add(train_map);

        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-22");
        train_map.put("trainNo", "3306");
        train_map.put("source", R.drawable.flg_shi);
        train_map.put("destination",R.drawable.flg_zhong);
        train_map.put("startTime","08:30");
        train_map.put("stopTime","20:39(0日)");
        train_map.put("seat1","硬卧:88");
        train_map.put("seat2", "硬座:241");
        train_map.put("seat3", "无座:64");
        train_map.put("seat4", null);
        trainInformation.add(train_map);
        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-22");
        train_map.put("trainNo","D78");
        train_map.put("source",R.drawable.flg_guo);
        train_map.put("destination",R.drawable.flg_guo);
        train_map.put("startTime","07:30");
        train_map.put("stopTime","15:39(0日)");
        train_map.put("seat1","一等座:96");
        train_map.put("seat2","二等座:15");
        train_map.put("seat3", "无座:35");
        train_map.put("seat4", null);
        trainInformation.add(train_map);
        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-22");
        train_map.put("trainNo","Z102");
        train_map.put("source",R.drawable.flg_guo);
        train_map.put("destination",R.drawable.flg_zhong);
        train_map.put("startTime","19:30");
        train_map.put("stopTime","14:49(1日)");
        train_map.put("seat1","软卧:72");
        train_map.put("seat2","硬卧:63");
        train_map.put("seat3", "硬座:84");
        train_map.put("seat4", "无座:27");
        trainInformation.add(train_map);
        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-22");
        train_map.put("trainNo","K277");
        train_map.put("source",R.drawable.flg_guo);
        train_map.put("destination",R.drawable.flg_guo);
        train_map.put("startTime","07:30");
        train_map.put("stopTime","15:39(0日)");
        train_map.put("seat1","软卧:164");
        train_map.put("seat2","硬卧:256");
        train_map.put("seat3","硬座:95");
        train_map.put("seat4", "无座:1");
        trainInformation.add(train_map);

        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-20");
        train_map.put("trainNo", "3306");
        train_map.put("source", R.drawable.flg_shi);
        train_map.put("destination",R.drawable.flg_zhong);
        train_map.put("startTime","08:30");
        train_map.put("stopTime","20:39(0日)");
        train_map.put("seat1","硬卧:214");
        train_map.put("seat2", "硬座:64");
        train_map.put("seat3", "无座:89");
        train_map.put("seat4", null);
        trainInformation.add(train_map);
        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-20");
        train_map.put("trainNo","D78");
        train_map.put("source",R.drawable.flg_guo);
        train_map.put("destination",R.drawable.flg_guo);
        train_map.put("startTime","07:30");
        train_map.put("stopTime","15:39(0日)");
        train_map.put("seat1","一等座:85");
        train_map.put("seat2","二等座:95");
        train_map.put("seat3", "无座:84");
        train_map.put("seat4", null);
        trainInformation.add(train_map);
        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-20");
        train_map.put("trainNo","Z102");
        train_map.put("source",R.drawable.flg_guo);
        train_map.put("destination",R.drawable.flg_zhong);
        train_map.put("startTime","19:30");
        train_map.put("stopTime","14:49(1日)");
        train_map.put("seat1","软卧:125");
        train_map.put("seat2","硬卧:84");
        train_map.put("seat3", "硬座:27");
        train_map.put("seat4", "无座:55");
        trainInformation.add(train_map);
        train_map = new HashMap<String, Object>();
        train_map.put("datetime", "2016-1-20");
        train_map.put("trainNo","K277");
        train_map.put("source",R.drawable.flg_guo);
        train_map.put("destination",R.drawable.flg_guo);
        train_map.put("startTime","07:30");
        train_map.put("stopTime","15:39(0日)");
        train_map.put("seat1","软卧:14");
        train_map.put("seat2","硬卧:0");
        train_map.put("seat3","硬座:42");
        train_map.put("seat4", "无座:84");
        trainInformation.add(train_map);
    }
}
